<h4 align="right">12th of February 2019</h4>
<h1 align="center">Neural Networks and Deep Learning (CIE 555)</h1>
<h2 align="center">Lab 2: TensorFlow</h2> <br>

In [1]:
import tensorflow as tf
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### TensorFlow basics

In [2]:
X = tf.constant(5)
Y = tf.constant(10)
S = tf.add(X,Y)
M = tf.multiply(X,Y)
Z = tf.subtract(M,S)

In [3]:
# sess = tf.Session
# print(sess.run(Z))
# sess.close()
with tf.Session() as sess:
    print(sess.run(Z))

35


In [4]:
# integrate with numpy and constants by converting numpy to constants
X = tf.constant(5)
Y = tf.constant(10)
S = X + 5
M = Y * 10
Z = tf.subtract(M,S)
with tf.Session() as sess:
    print(sess.run(Z))

90


In [5]:
# broadcasting applies
X = tf.constant(5)
Y = tf.constant(10)
S = X + [1,1,1,1]
M = Y * [5,5,5,5]
Z = tf.subtract(M,S)
# can get tensor dims
print(Z.get_shape().as_list())

with tf.Session() as sess:
    print(sess.run(Z))

[4]
[44 44 44 44]


In [6]:
# what if I need to feed data
tf.reset_default_graph()
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
S = tf.add(X,Y)
M = tf.multiply(X,Y)
Z = tf.subtract(M,S)
with tf.Session() as sess:
    print(sess.run(Z, feed_dict = {X:5,Y:10}))
#train_writer.add_graph(tf.get_default_graph())

35.0


In [7]:
a = tf.constant([2,2], name = 'a', dtype = tf.int32)
a = tf.zeros([2])
a = tf.zeros((2,), dtype = tf.int32)
b = tf.zeros_like(a)
a = tf.fill([2,2], 5)

In [8]:
# a = np.array([10,10])
a = np.array([[10,10],[1,1]])
b = np.array([[2, 2],[2, 2]])
c = tf.matmul(a,b)
with tf.Session() as sess:
    print(sess.run(c))

[[40 40]
 [ 4  4]]


In [9]:
# a = np.array([10,10])
a = np.array([[10,10],[1,1]])
b = np.array([[2, 2],[2, 2]])
c = tf.cast(tf.matmul(a,b), dtype = tf.float32)
with tf.Session() as sess:
    print(sess.run(c))

[[40. 40.]
 [ 4.  4.]]


<h3> Don't use tf.arange</h3>
doesn't work with for loops

### Regression example on boston dataset

In [10]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

In [11]:
boston = load_boston()
xtrain, xtest, ytrain, ytest = train_test_split(boston.data, boston.target.reshape(-1,1), test_size = 0.2, random_state = 1)

In [12]:


'''
epochs = 10000
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for i in range(epochs):
#         _, loss = sess.run([optimizer, loss], feed_dict = {X:xtrain}) beware of the loss variable
    _, loss_train, predictions = sess.run([optimizer, loss, preds], feed_dict = {X : xtrain, Y : ytrain})
    if i % 10 == 0:
        print(i, loss_train)
        
'''

'\nepochs = 10000\nsess = tf.Session()\nsess.run(tf.global_variables_initializer())\nfor i in range(epochs):\n#         _, loss = sess.run([optimizer, loss], feed_dict = {X:xtrain}) beware of the loss variable\n    _, loss_train, predictions = sess.run([optimizer, loss, preds], feed_dict = {X : xtrain, Y : ytrain})\n    if i % 10 == 0:\n        print(i, loss_train)\n        \n'

In [13]:
#testpreds = sess.run(preds, feed_dict = {X:xtest})
#loss_test = sess.run(loss, feed_dict = {Y:ytest, preds:testpreds})
#print('train loss',loss_train,'\ntest loss',loss_test)

In [14]:
sess.close()

### Classification practice on iris dataset

#### Data preparation

In [15]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [16]:
iris = load_iris()  # iris.data, iris.target
### To Be Done ### use sklearn OneHotEncoder grade = 5% time = 5 min  2 lines
onehotencoder1 = OneHotEncoder()
labels = onehotencoder1.fit_transform(iris.target.reshape(-1, 1).astype(np.float32)).toarray()  # <=== Change

##################
# labels are the encoded iris.target
xtrain, xtest, ytrain, ytest = train_test_split(iris.data, labels, test_size = 0.2, random_state = 1)
#ytrain_ori = onehotencoder1.inverse_transform(ytrain)
#ytest_ori = onehotencoder1.inverse_transform(ytest)
_, _, ytrain_ori, ytest_ori = train_test_split(iris.data, iris.target, test_size = 0.2, random_state = 1)


#### build model

In [17]:
### To be Done ### implement the four functions grade = 80% time = 1 hour  around 20 lines
def placeholders(nx,ny):
    X = tf.placeholder(tf.float32, shape=[None,nx])
    Y = tf.placeholder(tf.float32, shape=[None,ny])
    return X, Y
def init_weights():
    W1 = tf.get_variable("Weights1", shape = [4,5], initializer = tf.contrib.layers.xavier_initializer(seed = 5))
    W2 = tf.get_variable("weights2", shape = [5,3], initializer = tf.contrib.layers.xavier_initializer(seed = 5))
    b1 = tf.get_variable("bias1", initializer = tf.constant(0.0))
    b2 = tf.get_variable("bias2", initializer = tf.constant(0.0))
    return {'W1':W1,'W2':W2, 'b1':b1,'b2':b2}
def forward(X, params):
    W1 = params['W1']
    W2 = params['W2']
    b1 = params['b1']
    b2 = params['b2']
    Z1 = tf.add(tf.matmul(X,W1),b1)
    a1 = tf.nn.relu(Z1)
    Z2 = tf.add(tf.matmul(a1,W2),b2)
    a2 = tf.nn.softmax(Z2)
    return a2
def cost(A, Y):
    loss = tf.losses.softmax_cross_entropy(Y, A)
    return loss

#########################################################
def predict(A):
    return tf.round(A)
def accuracy(A, Y):
    preds = predict(A)
    return tf.metrics.accuracy(Y, preds)

In [18]:
tf.reset_default_graph()
X, Y = placeholders(xtrain.shape[1], ytrain.shape[1])
parameters = init_weights()
preds_proba = forward(X, parameters)
loss = cost(preds_proba, Y)
optimizer = tf.train.AdamOptimizer(learning_rate=0.001).minimize(loss)
preds = predict(preds_proba)
acc = accuracy(preds_proba, Y)

In [19]:
epochs = 10000
sess = tf.Session()
sess.run(tf.local_variables_initializer())
sess.run(tf.global_variables_initializer())
for i in range(epochs):
#         _, loss = sess.run([optimizer, loss], feed_dict = {X:xtrain}) beware of the loss variable
    _, loss_train, acc_train, predictions = sess.run([optimizer, loss, acc, preds], feed_dict = {X : xtrain, Y : ytrain})
    if i % 500 == 0:
        print(i, loss_train, acc_train[0])

0 1.1280918 0.0
500 0.7579782 0.7653889
1000 0.62975705 0.87040275
1500 0.6003466 0.9069389
2000 0.5904035 0.9260375
2500 0.5854805 0.93749666
3000 0.5823113 0.94513613
3500 0.57900536 0.9505929
4000 0.57713884 0.954691
4500 0.5749103 0.9583796
5000 0.5728451 0.96143055
5500 0.57132816 0.9639268
6000 0.5703036 0.96600693
6500 0.5696115 0.9677671
7000 0.56914526 0.9692758
7500 0.56883013 0.9705833
8000 0.5686161 0.97172743
8500 0.5684694 0.97273695
9000 0.56836766 0.97363424
9500 0.5682964 0.9744371


#### Validate

In [20]:
### To be Done ### get test accuracy grade = 15% time = 20 min   4 lines
X, Y = placeholders(xtest.shape[1], ytest.shape[1])
#parameters = init_weights()
preds_proba = forward(X, parameters)
preds = predict(preds_proba)
acc = accuracy(preds_proba, Y)
#sess = tf.Session()
sess.run(tf.local_variables_initializer())
#sess.run(tf.global_variables_initializer())
test_acc, test_predictions = sess.run([acc, preds], feed_dict = {X : xtest, Y : ytest})
print(test_acc)

#####################################################################

(0.0, 0.95555556)


In [21]:
# another accuracy method
from sklearn.metrics import accuracy_score
test_predictions = np.argmax(test_predictions, axis = 1)
train_predictions = np.argmax(predictions, axis = 1)
print('train accuracy', accuracy_score(train_predictions, ytrain_ori))
print('test accuracy', accuracy_score(test_predictions, ytest_ori))

train accuracy 0.9833333333333333
test accuracy 0.9333333333333333


### multiple Graphs

In [22]:
# multiple graphs
tf.reset_default_graph()
g = tf.Graph()
with g.as_default():
    X = tf.constant(5)
    Y = tf.constant(10)
    S = tf.add(X,Y)
    M = tf.multiply(X,Y)
    Z = tf.subtract(M,S)
with tf.Session(graph = g) as sess:
    print(sess.run(Z))
g2 = tf.Graph()
with g2.as_default():
    X = tf.placeholder(tf.float32)
    Y = tf.placeholder(tf.float32)
    S = tf.add(X,Y)
    M = tf.multiply(X,Y)
    Z = tf.subtract(M,S)
with tf.Session(graph = g2) as sess:
    print(sess.run(Z, feed_dict = {X:5,Y:10}))
    
# How will you share variables?
# Why?
# editing others code

35
35.0
